project_id = "infrastructure"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = false
port = 54324

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB").
enabled = false
file_size_limit = "50MiB"

[auth]
enabled = false

[auth.email]
enable_signup = false

[auth.sms]
enable_signup = false

[auth.sms.twilio]
enabled = false

[analytics]
enabled = false
