project_id = "grttzpnchqelszmwhxhu"

[api]
enabled = false
# port = 54321
# schemas = ["public"]
# extra_search_path = ["public"]
# max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = false
# port = 54323
# api_url = "http://localhost"

[inbucket]
enabled = false

[storage]
enabled = false
# The maximum file size allowed (e.g. "5MB", "500KB").
# file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = false

[analytics]
enabled = false
